# .travis.yml

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  include:
    - env: BASE_OS=alpine
    - env: BASE_OS=debian

script:
  - docker build --pull -t fretlink/nix -f ${BASE_OS}/Dockerfile .
  - docker run -it --rm fretlink/nix 'nix-channel --list'
  - docker run -it --rm fretlink/nix 'nix-env -iA nixpkgs.hello && test "$(hello)" = "Hello, world!"'
